// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20240704203929_V3")]
    partial class V3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Licna")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("WebTemplate.Models.KorisnikTura", b =>
                {
                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int>("TuraID")
                        .HasColumnType("int");

                    b.HasKey("KorisnikID", "TuraID");

                    b.HasIndex("TuraID");

                    b.ToTable("KorisnikTure");
                });

            modelBuilder.Entity("WebTemplate.Models.Tura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Ture");
                });

            modelBuilder.Entity("WebTemplate.Models.Znamenitost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Znamenitosti");
                });

            modelBuilder.Entity("WebTemplate.Models.ZnamenitostTura", b =>
                {
                    b.Property<int>("ZnamenitostID")
                        .HasColumnType("int");

                    b.Property<int>("Turaid")
                        .HasColumnType("int");

                    b.HasKey("ZnamenitostID", "Turaid");

                    b.HasIndex("Turaid");

                    b.ToTable("ZnamenitostTure");
                });

            modelBuilder.Entity("WebTemplate.Models.KorisnikTura", b =>
                {
                    b.HasOne("WebTemplate.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebTemplate.Models.Tura", "Tura")
                        .WithMany()
                        .HasForeignKey("TuraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Tura");
                });

            modelBuilder.Entity("WebTemplate.Models.ZnamenitostTura", b =>
                {
                    b.HasOne("WebTemplate.Models.Tura", "Tura")
                        .WithMany()
                        .HasForeignKey("Turaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebTemplate.Models.Znamenitost", "Znamenitost")
                        .WithMany()
                        .HasForeignKey("ZnamenitostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tura");

                    b.Navigation("Znamenitost");
                });
#pragma warning restore 612, 618
        }
    }
}
